### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danaiamirali** [danaiamirali/spec-to-tex#3]
GPT4V:
- [] Add page-by-page mode where the model does conversion for each individual page in the provided document, and then link the generated TeX into one final version 
- [] Add version where you can provide a LaTeX template on the command-line for the model to adhere to as it generates

LlamaParse:
- [] Evaluate whether this is even worth it or good
- [] Add Linker func to combine LlamaParse outputs since LlamaParse treats every page from a PDF as a separate document, leading to output that needs to be corrected
